apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigil-observer
  namespace: default
  labels:
    app: vigil-observer
    component: monitoring
    tier: data-collection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vigil-observer
  template:
    metadata:
      labels:
        app: vigil-observer
        component: monitoring
        tier: data-collection
    spec:
      containers:
      - name: observer-agent
        image: gcr.io/vigil-demo-hackathon/vigil-observer-agent:latest
        ports:
        - containerPort: 8000
          name: a2a-port
        env:
        - name: MCP_SERVER_PATH
          value: "/app/vigil_mcp_lowlevel.py"
        - name: OBSERVER_PORT
          value: "8000"
        - name: ANALYST_AGENT_URL
          value: "http://vigil-analyst:8001"
        - name: POLLING_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: vigil-config
              key: polling_interval
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: vigil-config
              key: batch_size
        # Bank of Anthos service endpoints (same namespace now)
        - name: LEDGER_WRITER_URL
          value: "http://ledgerwriter:8080"
        - name: TRANSACTION_HISTORY_URL
          value: "http://transactionhistory:8080"
        - name: BALANCE_READER_URL
          value: "http://balancereader:8080"
        - name: CONTACTS_URL
          value: "http://contacts:8080"
        - name: USER_SERVICE_URL
          value: "http://userservice:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: logs-volume
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vigil-observer
  namespace: default
  labels:
    app: vigil-observer
spec:
  selector:
    app: vigil-observer
  ports:
  - name: a2a-port
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP