apiVersion: v1
kind: ConfigMap
metadata:
  name: vigil-config
  namespace: default
  labels:
    app: vigil-system
    component: configuration
data:
  # Risk assessment configuration
  risk_threshold: "75"
  
  # Observer configuration
  polling_interval: "5"  # seconds
  batch_size: "100"
  
  # Action execution settings
  auto_execute_actions: "false"  # Set to true for production with proper safeguards
  
  # Fraud detection settings
  confidence_minimum: "0.3"
  
  # Monitoring configuration
  enable_metrics: "true"
  log_level: "INFO"
  
  # A2A communication settings
  a2a_timeout: "30"  # seconds
  
  # Regional settings for Latin America focus
  target_regions: "BR,MX,CO,AR,CL"
  
  # PIX-specific fraud patterns (Brazil)
  pix_keywords: "emergencia,urgente,hospital,acidente,ajuda"
  
  analyst-config.yaml: |
    agent:
      name: "vigil_analyst_agent"
      model: "gemini-2.5-flash"
      version: "1.0"
      risk_threshold: 75
      confidence_minimum: 0.3
    fraud_detection:
      regions:
        - "Brazil"
        - "Mexico"
        - "Colombia"
        - "Argentina"
        - "Chile"
      high_risk_categories:
        - "gambling"
        - "adult_content"
        - "crypto_exchange"
        - "cash_advance"
        - "money_transfer"
    logging:
      level: "INFO"
      structured_output: true
      log_sensitive_data: false
---
apiVersion: v1
kind: Secret
metadata:
  name: vigil-secrets
  namespace: default
  labels:
    app: vigil-system
    component: secrets
type: Opaque
data:
  # Base64 encoded API key - replace with actual values
  # To encode: echo -n "your-actual-api-key" | base64
  gemini-api-key: "eW91ci1hY3R1YWwtZ2VtaW5pLWFwaS1rZXktaGVyZQ=="