# Vigil Analyst Agent Configuration

agent:
  name: "vigil_analyst_agent"
  model: "gemini-2.5-flash"
  version: "1.0"
  
  # A2A Communication settings
  a2a_port: 8001
  enable_a2a: true
  
  # Risk assessment settings
  risk_threshold: 75  # Alert threshold for forwarding to Actuator
  confidence_minimum: 0.3  # Minimum confidence for analysis
  
  # MCP Server configuration
  mcp:
    server_path: "/app/vigil_mcp_lowlevel.py"
    transport: "stdio"
    timeout: 30
    tools:
      - "get_transactions" 
      - "get_user_details"
      - "lock_account"
  
  # Cache settings
  cache:
    enabled: true
    max_entries: 1000
    ttl_seconds: 300  # 5 minutes

# Fraud detection configuration
fraud_detection:
  # Regional focus
  regions:
    - "Brazil"
    - "Mexico" 
    - "Colombia"
    - "Argentina"
    - "Chile"
  
  # Risk factors and weights
  risk_factors:
    geographic_impossibility: 0.25
    velocity_anomaly: 0.20
    amount_anomaly: 0.20
    recipient_risk: 0.15
    time_anomaly: 0.10
    device_change: 0.10
  
  # Transaction categories by risk level
  high_risk_categories:
    - "gambling"
    - "adult_content"
    - "crypto_exchange"
    - "cash_advance"
    - "money_transfer"
  
  # PIX-specific fraud patterns (Brazil)
  pix_patterns:
    social_engineering_keywords:
      - "emergencia"
      - "urgente"
      - "hospital"
      - "acidente"
      - "ajuda"
    fake_merchant_indicators:
      - "random_alphanumeric"
      - "temporary_account"
      - "recent_creation"

# Communication with other agents
agents:
  observer:
    name: "vigil_observer_agent"
    port: 8000
    endpoint: "/transaction_data"
  
  actuator: 
    name: "vigil_actuator_agent"
    port: 8002
    endpoint: "/fraud_alert"

# Logging configuration  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Structured logging for analysis results
  structured_output: true
  
  # Log sensitive data (disable in production)
  log_sensitive_data: false

# Monitoring and observability
monitoring:
  metrics_enabled: true
  health_check_port: 8091
  
  # Alert thresholds
  alerts:
    high_risk_rate_threshold: 0.1  # 10% high-risk transactions
    analysis_latency_threshold: 5.0  # seconds
    error_rate_threshold: 0.05  # 5% error rate

# Development and testing
development:
  test_mode: false
  mock_mcp: false
  simulate_latency: false
  debug_prompts: false