apiVersion: v1
kind: Service
metadata:
  name: investigation-agent-service
spec:
  selector:
    app: investigation-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
