apiVersion: apps/v1
kind: Deployment
metadata:
  name: critic-agent
  labels:
    app: critic-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: critic-agent
  template:
    metadata:
      labels:
        app: critic-agent
    spec:
      containers:
      - name: critic-agent
        # Replace with the actual image path after building and pushing
        image: southamerica-east1-docker.pkg.dev/vigil-demo-hackathon/vigil-repo/critic-agent:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: key
