apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-agent
  labels:
    app: orchestrator-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-agent
  template:
    metadata:
      labels:
        app: orchestrator-agent
    spec:
      containers:
      - name: orchestrator-agent
        # Replace with the actual image path after building and pushing
        image: southamerica-east1-docker.pkg.dev/vigil-demo-hackathon/vigil-repo/orchestrator-agent:v20250922-g26
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: INVESTIGATION_AGENT_SERVICE_URL
          value: "http://investigation-agent-service"
        - name: ACTUATOR_AGENT_SERVICE_URL
          value: "http://actuator-agent-service"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: key
        - name: RISK_SCORE_THRESHOLD
          value: "7"
