# Cloud Run deployment configuration for Vigil MCP Server
# Supports both ADK agents and standalone MCP clients

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vigil-mcp-server
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Enable HTTP/2 for better MCP streaming performance
        run.googleapis.com/execution-environment: gen2
        # Adjust for MCP connection requirements
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/vigil-mcp-server:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: BANK_BASE_URL
          value: "http://frontend.bank-of-anthos.svc.cluster.local"
        - name: REQUEST_TIMEOUT
          value: "30"
        - name: AUTH_USERNAME
          value: "admin"
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vigil-secrets
              key: AUTH_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: vigil-secrets
              key: JWT_SECRET
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        # MCP servers need persistent connections
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      # Allow for longer-lived connections (important for MCP)
      timeoutSeconds: 3600